In [1]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [2]:
x_set=list(range(0,10,1))
y_set=list(range(0,100,10))

In [3]:
print(x_set)
print(y_set)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [4]:
x_train, x_test, y_train, y_test = train_test_split(x_set, y_set, test_size=0.33, random_state=42)

In [5]:
print(x_train)
print(y_train)

[7, 2, 9, 4, 3, 6]
[70, 20, 90, 40, 30, 60]


In [6]:
print(x_test)
print(y_test)

[8, 1, 5, 0]
[80, 10, 50, 0]


In [7]:
np_test=np.array(x_set)
print(np_test.max())
print(np_test.mean())
print(np_test.std())

9
4.5
2.8722813232690143


In [8]:
dir(np_test)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [9]:
older={'uno': [1,2],
   'dos': [3,4]}

In [10]:
newer={'uno': [5,6],
      'dos': [7,8]}

In [11]:
pd_older = pd.DataFrame.from_dict(older)

In [12]:
pd_newer = pd.DataFrame.from_dict(newer)

In [13]:
print(pd_older)
print(pd_newer)

   uno  dos
0    1    3
1    2    4
   uno  dos
0    5    7
1    6    8


In [14]:
vertical_stack = pd.concat([pd_older, pd_newer], axis=0)

In [15]:
print(vertical_stack)

   uno  dos
0    1    3
1    2    4
0    5    7
1    6    8


In [16]:
pd_older-pd_newer

uno  dos
0   -4   -4
1   -4   -4

In [17]:
older={'uno': [1,2],
   'dos': [10,5]}
newer={'uno': [5,0],
      'dos': [3,8]}
pd_older = pd.DataFrame.from_dict(older)
pd_newer = pd.DataFrame.from_dict(newer)

In [18]:
pd_older

uno  dos
0    1   10
1    2    5

In [19]:
pd_newer

uno  dos
0    5    3
1    0    8

In [20]:
pd_older-pd_newer

uno  dos
0   -4    7
1    2   -3

In [21]:
import pickle
INPUT_DATASET='./env_data/diff/x_set_diff.pickle'
OUTPUT_DATASET='./env_data/diff/y_set_diff.pickle'

with open(INPUT_DATASET, 'rb') as f:
    x_set = pickle.load(f)
    print("I load x_set")
with open(OUTPUT_DATASET, 'rb') as f:
    y_set = pickle.load(f)
    print("I load y_set")

I load x_set
I load y_set


In [22]:
y_set.shape

(494624, 30)

In [23]:
pd_newer.shape

(2, 2)

In [24]:
np_data=np.arange(20)
np_data=np_data.reshape(10,2)
print(np_data)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [25]:
rdf=pd.DataFrame(np_data,columns=['uno','dos'])

In [26]:
rdf

uno  dos
0    0    1
1    2    3
2    4    5
3    6    7
4    8    9
5   10   11
6   12   13
7   14   15
8   16   17
9   18   19

In [27]:
shift=2
elements=len(rdf)
print(np.arange(0,10,2))
locator=np.arange(0, elements, shift)

[0 2 4 6 8]


In [28]:
rdf.iloc[locator,:]

uno  dos
0    0    1
2    4    5
4    8    9
6   12   13
8   16   17

In [29]:
np_data[np.arange(0,10,2)]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [31]:
np_data[0][1]

1

In [32]:
x=np_data

In [33]:
shift=2
last=len(x)-shift
print(last)

8


In [34]:
y=np_data[np.arange(0,len(x),shift)]
print(y)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]


In [35]:
def shift_data_old(input_ds,output_ds,shift):
    locator=np.arange(0, len(input_ds), shift)
    print(locator)
    in_ds_shift=input_ds[0:len(input_ds)-shift,:]
    out_ds_shift=output_ds[locator]
    print("Shift is:",shift)
    print("Input Shape:", in_ds_shift.shape)
    print("Output Shape:", out_ds_shift.shape)
    return in_ds_shift,out_ds_shift

In [36]:
t=np.zeros((2,3))
print(t)

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
t[1]=[1,2,3]

In [38]:
t[:,1::]

array([[0., 0.],
       [2., 3.]])

In [39]:
def shift_data_old2(input_ds,output_ds,shift):
    locator=np.arange(0, len(input_ds), shift)
    in_ds_shift=input_ds[0:len(input_ds)-shift,:]
    out_ds_shift=np.zeros(in_ds_shift.shape)
    for i in range(len(in_ds_shift)):
        out_ds_shift[i]=output_ds[i+shift,:]
    print("Shift is:%s \n Input Shape:%s \n Output Shape:%s"%(shift,in_ds_shift.shape,out_ds_shift.shape))
    return in_ds_shift,out_ds_shift

In [40]:
def shift_data(input_ds,output_ds,shift):
    locator=np.arange(0, len(input_ds), shift)
    in_ds_shift=input_ds[0:len(input_ds)-shift,:]
    out_ds_shift=output_ds[shift::,:]
    print("Shift is:%s \n Input Shape:%s \n Output Shape:%s"%(shift,in_ds_shift.shape,out_ds_shift.shape))
    return in_ds_shift,out_ds_shift

In [41]:
s_in,s_out=shift_data(x_set,y_set,shift=3)

Shift is:3 
 Input Shape:(494621, 38) 
 Output Shape:(494621, 30)


In [42]:
print(x_set)
print(5*"*")
print(s_in)

[[1998.030518   2000.000366    160.3250275  ...   82.73389435
     3.41233397   39.11010742]
 [2001.770142   2000.000977    160.3579559  ...   82.73149109
     3.40727234   39.27136993]
 [2003.749268   2000.001709    160.3852234  ...   83.05037689
     3.40911126   39.37528229]
 ...
 [2091.254639   2083.137207    164.9241791  ...   84.35935211
     3.80847549   37.7918663 ]
 [2088.333008   2083.137695    164.9267578  ...   84.36689758
     3.80079579   37.85303116]
 [2089.855469   2083.137939    164.9235077  ...   84.3693161
     3.77875304   37.76679611]]
*****
[[1998.030518   2000.000366    160.3250275  ...   82.73389435
     3.41233397   39.11010742]
 [2001.770142   2000.000977    160.3579559  ...   82.73149109
     3.40727234   39.27136993]
 [2003.749268   2000.001709    160.3852234  ...   83.05037689
     3.40911126   39.37528229]
 ...
 [2080.616211   2083.136475    164.8687592  ...   83.76983643
     3.72734666   37.57106018]
 [2085.911377   2083.136719    164.8889923  ...   83.7

In [43]:
print(y_set)
print(5*"*")
print(s_out)

[[ 4.51855400e+00 -2.06895142e+01  2.29493000e-02 ... -2.40326000e-03
  -5.06162600e-03  1.61262510e-01]
 [ 7.47680670e+01  1.93644410e+01  1.23260500e-01 ...  3.18885800e-01
   1.83892200e-03  1.03912360e-01]
 [-1.20193848e+02 -3.66784670e+00 -1.74866000e-02 ... -5.11170000e-04
   9.73248500e-03  3.44734200e-02]
 ...
 [-2.30463870e+01  5.33764650e+00 -1.19781500e-01 ...  7.54547000e-03
  -7.67970000e-03  6.11648600e-02]
 [-3.05859300e+00 -3.86669920e+00 -9.22547000e-02 ...  2.41852000e-03
  -2.20427520e-02 -8.62350500e-02]
 [ 3.28613200e+00  2.54797360e+00 -8.51135000e-02 ... -1.62506000e-03
  -3.06773200e-03 -1.98177340e-01]]
*****
[[ 6.50756840e+01 -1.44656372e+01  1.13220200e-01 ...  1.10626000e-03
   3.30972700e-03 -1.40571600e-02]
 [ 4.67202150e+01  1.55831299e+01  6.16150000e-02 ... -1.14440000e-04
  -2.64978400e-03  4.28085300e-02]
 [-6.58154300e+00  4.33892820e+00  5.58777000e-02 ...  2.57874000e-03
   8.10527800e-03 -2.28538500e-02]
 ...
 [-2.30463870e+01  5.33764650e+00 -1.1

In [44]:
x_set=np.arange(0,200,10)
x_set=x_set.reshape(10,2)
print(x_set)

[[  0  10]
 [ 20  30]
 [ 40  50]
 [ 60  70]
 [ 80  90]
 [100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [45]:
y_set=np_data
print(y_set)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [46]:
s_in,s_out=shift_data(x_set,y_set,shift=3)

Shift is:3 
 Input Shape:(7, 2) 
 Output Shape:(7, 2)


In [47]:
print(x_set)
print(5*"*")
print(s_in)

[[  0  10]
 [ 20  30]
 [ 40  50]
 [ 60  70]
 [ 80  90]
 [100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
*****
[[  0  10]
 [ 20  30]
 [ 40  50]
 [ 60  70]
 [ 80  90]
 [100 110]
 [120 130]]


In [48]:
print(y_set)
print(5*"*")
print(s_out)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
*****
[[ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [49]:
import datetime
t=datetime.datetime.now()
print(t)

2020-04-17 19:26:50.841483


In [50]:
import time
time.strftime('%B_%d_%H%M%S')

'April_17_192650'

In [51]:
A=np.arange(0,6)
A=A.reshape(3,2)

In [52]:
print(A)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
B=np.arange(7,13)
B=B.reshape(3,2)

In [54]:
print(B)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [55]:
out=np.concatenate((A,B),axis=1)
print(out)

[[ 0  1  7  8]
 [ 2  3  9 10]
 [ 4  5 11 12]]


In [56]:
a=out[:,0:2]
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [57]:
b=out[:,2:4]
print(b)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [58]:
out.shape

(3, 4)

In [59]:
b[1:3,:]

array([[ 9, 10],
       [11, 12]])

In [60]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])