In [1]:
import numpy as np
import pandas as pd

In [2]:
def split_data(data_df, as_dic=False):
    full_state_trace = np.array(data_df[state_names])
    full_action_trace = np.array(data_df[action_names])
    actions_input=np.array(data_df[action_names].iloc[0:len(data_df)-1,:]) #skip last row
    states_input=np.array(data_df[state_names].iloc[0:len(data_df)-1,:]) #skip last row
    states_output=np.array(data_df[state_names].iloc[1::,:]) #skip fist row
    states_diff = states_output-states_input
    diff_out=pd.DataFrame(data=states_diff,columns=state_names)
    print("Actions input shape:",actions_input.shape)
    print("State input shape:",states_input.shape)
    print("State output shape:",states_output.shape)
    print("State difference shape:",states_diff.shape)
    print("Diff_out df shape:",diff_out.shape)
    print("full_action_trace",full_action_trace.shape)
    print("full_state_trace:",full_state_trace.shape)
    data_dic={'actions_input':actions_input, 
                'states_input':states_input,
                'states_output':states_output,
                'states_diff':states_diff,
                'diff_out': diff_out,
                'full_action_trace':full_action_trace,
                'full_state_trace':full_state_trace
                    }
    if as_dic:
        print('Return dictionary keys: \n',data_dic.keys())
        return data_dic
    print('Return a list with: [actions_input, states_input,states_output,states_diff, diff_out,full_action_trace,full_state_trace]')
    return actions_input, states_input,states_output,states_diff, diff_out,full_action_trace,full_state_trace

In [3]:
def shift_data(input_ds,output_ds,shift):
    locator=np.arange(0, len(input_ds), shift)
    in_ds_shift=input_ds[0:len(input_ds)-shift,:]
    out_ds_shift=output_ds[shift::,:]
    print("Shift is:%s \n Input Shape:%s \n Output Shape:%s"%(shift,in_ds_shift.shape,out_ds_shift.shape))
    return in_ds_shift,out_ds_shift

In [4]:
def get_diff(actions,states,shift,verbose=False):
    a_in=actions[0:len(states)-shift,:]
    s_in=states[0:len(states)-shift,:]
    s_out=states[shift::,:]
    s_diff=s_out-s_in
    a_s_in=np.concatenate((a_in,s_in),axis=1)
    if verbose:
        print('original_input\n',states)
        print('states cut\n',s_in)
        print('states shift\n',s_out)
        print('diff\n',s_diff)
        print('action_state_input\n',a_s_in)
    return s_in,s_out,s_diff,a_s_in  

In [5]:
def get_shift_cut(actions,states,shift):
    _,num_actions_columns=actions.shape
    a_s_in=np.concatenate((actions,states),axis=1)
    print('a_s_shift\n',a_s_in)
    r,c=a_s_in.shape #rows, columns
    n=r//shift
    a_s_shift=np.zeros((n,c))
    #print(a_s_shift.shape)
    #print(n)
    for i in range(1,n):
        print(i)
        a_s_shift[i,:]=a_s_in[i*shift,:]
    x_set=a_s_shift[0:-1,:]
    y_set=a_s_shift[1::,num_actions_columns::]
    return a_s_shift,x_set,y_set

In [6]:
nrows=11
a=np.arange(0,nrows-1)

In [7]:
data={'a1':a,'s1':a,'s2':a}

In [8]:
df1=pd.DataFrame.from_dict(data)
#print(df1)

In [9]:
df2=df1*10
#print(df2)

In [10]:
print(df1.to_numpy())
print(df2.to_numpy())

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [40 40 40]
 [50 50 50]
 [60 60 60]
 [70 70 70]
 [80 80 80]
 [90 90 90]]


In [11]:
in_ds_shift,out_ds_shift=shift_data(df1.to_numpy(),df2.to_numpy(),5)
print(4*'*')
print(in_ds_shift)
print(4*'*')
print(out_ds_shift)

Shift is:5 
 Input Shape:(5, 3) 
 Output Shape:(5, 3)
****
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
****
[[50 50 50]
 [60 60 60]
 [70 70 70]
 [80 80 80]
 [90 90 90]]


## Split Dataset

In [12]:
action_names=['a1']

In [13]:
state_names = ['s1','s2']

In [14]:
##df3.iloc[ind,:]=df3.iloc[0,:]+df3.iloc[0+1,:]
#len(df3)

In [15]:
df3=df1
for ind in df3.index:
    df3.iloc[ind,:]=df3.iloc[ind,:]*ind
print(df3)

   a1  s1  s2
0   0   0   0
1   1   1   1
2   4   4   4
3   9   9   9
4  16  16  16
5  25  25  25
6  36  36  36
7  49  49  49
8  64  64  64
9  81  81  81


In [16]:
data_split_dic=split_data(df3,as_dic=True)

Actions input shape: (9, 1)
State input shape: (9, 2)
State output shape: (9, 2)
State difference shape: (9, 2)
Diff_out df shape: (9, 2)
full_action_trace (10, 1)
full_state_trace: (10, 2)
Return dictionary keys: 
 dict_keys(['actions_input', 'states_input', 'states_output', 'states_diff', 'diff_out', 'full_action_trace', 'full_state_trace'])


In [17]:
data_split_dic.keys()

dict_keys(['actions_input', 'states_input', 'states_output', 'states_diff', 'diff_out', 'full_action_trace', 'full_state_trace'])

In [18]:
#data_split_dic['diff_out']
#data_split_dic['states_diff']
data_split_dic['states_output']

array([[ 1,  1],
       [ 4,  4],
       [ 9,  9],
       [16, 16],
       [25, 25],
       [36, 36],
       [49, 49],
       [64, 64],
       [81, 81]])

In [19]:
data_split_dic

{'actions_input': array([[ 0],
        [ 1],
        [ 4],
        [ 9],
        [16],
        [25],
        [36],
        [49],
        [64]]),
 'states_input': array([[ 0,  0],
        [ 1,  1],
        [ 4,  4],
        [ 9,  9],
        [16, 16],
        [25, 25],
        [36, 36],
        [49, 49],
        [64, 64]]),
 'states_output': array([[ 1,  1],
        [ 4,  4],
        [ 9,  9],
        [16, 16],
        [25, 25],
        [36, 36],
        [49, 49],
        [64, 64],
        [81, 81]]),
 'states_diff': array([[ 1,  1],
        [ 3,  3],
        [ 5,  5],
        [ 7,  7],
        [ 9,  9],
        [11, 11],
        [13, 13],
        [15, 15],
        [17, 17]]),
 'diff_out':    s1  s2
 0   1   1
 1   3   3
 2   5   5
 3   7   7
 4   9   9
 5  11  11
 6  13  13
 7  15  15
 8  17  17,
 'full_action_trace': array([[ 0],
        [ 1],
        [ 4],
        [ 9],
        [16],
        [25],
        [36],
        [49],
        [64],
        [81]]),
 'full_state_trace': array([[

# Shift Difference

In [20]:
a=df1.to_numpy()[:,0:2]*10 #Mock acions
print(a)

[[  0   0]
 [ 10  10]
 [ 40  40]
 [ 90  90]
 [160 160]
 [250 250]
 [360 360]
 [490 490]
 [640 640]
 [810 810]]


In [21]:
df1.to_numpy()[0:3,:]

array([[0, 0, 0],
       [1, 1, 1],
       [4, 4, 4]])

In [22]:
df2.to_numpy()[0:3,:]

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20]])

In [23]:
shift=2
#get_diff(actions=a,states=df1.to_numpy(),shift=shift,verbose=True)

In [24]:
#print(df1.to_numpy())
total,x,y=get_shift_cut(actions=df1.to_numpy(),states=df2.to_numpy(),shift=shift)

a_s_shift
 [[ 0  0  0  0  0  0]
 [ 1  1  1 10 10 10]
 [ 4  4  4 20 20 20]
 [ 9  9  9 30 30 30]
 [16 16 16 40 40 40]
 [25 25 25 50 50 50]
 [36 36 36 60 60 60]
 [49 49 49 70 70 70]
 [64 64 64 80 80 80]
 [81 81 81 90 90 90]]
1
2
3
4


In [25]:
print(total)

[[ 0.  0.  0.  0.  0.  0.]
 [ 4.  4.  4. 20. 20. 20.]
 [16. 16. 16. 40. 40. 40.]
 [36. 36. 36. 60. 60. 60.]
 [64. 64. 64. 80. 80. 80.]]


In [26]:
print(x)

[[ 0.  0.  0.  0.  0.  0.]
 [ 4.  4.  4. 20. 20. 20.]
 [16. 16. 16. 40. 40. 40.]
 [36. 36. 36. 60. 60. 60.]]


In [27]:
print(y)

[[20. 20. 20.]
 [40. 40. 40.]
 [60. 60. 60.]
 [80. 80. 80.]]
